### **1. 넘파이 배열 생성**

In [ ]:
#코드 6-1
import numpy as np

#리스트를 생성하고 배열로 변환하기
list1 = [1, 2, 3, 4]
a = np.array(list1)
print('a.shape: ', a.shape)
print('a[0]: ', a[0])

#2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])
print('b.shape: ', b.shape)
print('b[0,0]: ', b[0,0])
print('b[0]: ', b[0])

In [ ]:
#코드 6-2
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2,2))
print('b\n', b)
c = np.ones((2,3))
print('c\n', c)
d = np.full((2,3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

In [ ]:
#코드 6-3
#실수형 배열 생성하기
a = np.array([1, 2], dtype=np.float64)
print(a.dtype)

#정수형 배열로 변환하기
a_i8 = a.astype(np.int8)
print(a_i8.dtype)

In [ ]:
#코드 6-4
arr = np.array([[0, 1, 2], [3, 4, 5]])

print('type(arr):',type(arr))
print('arr.ndim:',arr.ndim)
print('arr.dtype:',arr.dtype)
print('arr.itemsize:',arr.itemsize)
print('arr.size:',arr.size)
print('arr.nbytes:',arr.nbytes)
print('arr.T:\n',arr.T)
print('arr.shape:',arr.shape)

In [ ]:
#코드 6-5
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)

#다차원 배열로 변경하기
a.shape = (2,4)
print('shape\n', a)

#1차원 배열로 변경하기
print('flatten\n', a.flatten())

#resize 함수로 모양 변경하기
a.resize((4,2))
print('resize\n', a)

In [ ]:
#코드 6-6
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

b = a.transpose()
print('b\n', b)
c = a.T
print('c\n', c)

### **2. 배열 원소 조회 및 정렬**

In [ ]:
#코드 6-7
mask = np.array([0, 1, 1, 0], dtype=bool)
print(mask)

data = np.random.randn(4,2)
print('\ndata 출력\n',data) #랜덤 데이터 배열 data는 책과 다르게 나타남

print('\n마스킹된 데이터 출력\n',data[mask])
print('\n마스킹 역전된 데이터 출력\n',data[~mask])

In [ ]:
#코드 6-8
posit = data[data > 0]
print('양수 데이터 출력', '\n',posit)

#다중 조건
over1 = data[1][data[1] > 0]
print('두 번째 행의 양수 데이터 출력','\n',over1)

In [ ]:
#코드 6-9
a = np.arange(6)
b = a
print(a)
print(b is a)

b[0] = 10
print(a)

In [ ]:
#코드 6-10
a = np.arange(6)
c = a.copy()

c[0] = 20
print('A: ', a)
print('C: ', c)

In [ ]:
#코드 6-11
a = np.array([3, 2, 5, 1, 4])

print('원본\n',a)
print('정렬 후\n',np.sort(a))

print('원본\n',a)
print('정렬한 인덱스\n',np.argsort(a))

a.sort()
print('원본\n',a)

원본
 [3 2 5 1 4]
정렬 후
 [1 2 3 4 5]
원본
 [3 2 5 1 4]
정렬한 인덱스
 [3 1 0 4 2]
원본
 [1 2 3 4 5]
